import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "AI Fitness Coach",
  description: "Personalized workout and nutrition plans generated by AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased font-sans`}>
        <div className="min-h-screen flex flex-col bg-zinc-50 dark:bg-black">
          <header className="border-b bg-white/60 dark:bg-black/60 border-zinc-200 dark:border-zinc-800">
            <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
              <div className="flex items-center gap-3">
                <span className="inline-block h-8 w-8 rounded-md bg-gradient-to-br from-indigo-500 to-pink-500" />
                <span className="text-lg font-semibold text-zinc-900 dark:text-zinc-50">AI Fitness Coach</span>
              </div>
              <nav className="text-sm text-zinc-600 dark:text-zinc-300">
                <a className="mr-4 hover:underline" href="#">Home</a>
                <a className="mr-4 hover:underline" href="#plans">Plans</a>
                <a className="hover:underline" href="#about">About</a>
              </nav>
            </div>
          </header>

          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
