import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "AI Fitness Coach",
  description: "Personalized workout and nutrition plans generated by AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased font-sans`}>
        <div className="min-h-screen flex flex-col">
          {/* Full-width header with backdrop blur */}
          <header className="fixed top-0 left-0 right-0 z-50 w-full bg-black/40 backdrop-blur-md border-b border-white/10">
            <div className="mx-auto max-w-7xl flex items-center justify-between px-6 h-16">
              {/* Logo - aligned to far left */}
              <a href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
                <span className="inline-block h-8 w-8 rounded-lg bg-gradient-to-br from-cyan-500 to-indigo-600 shadow-lg" />
                <span className="text-lg font-bold text-white">AI Fitness Coach</span>
              </a>
              
              {/* Navigation - aligned to far right */}
              <nav className="flex items-center gap-6 text-sm font-medium text-slate-300">
                <a className="hover:text-white transition-colors" href="/">Home</a>
                <a className="hover:text-white transition-colors" href="/saved">Saved Plans</a>
                <a className="hover:text-white transition-colors" href="#about">About</a>
              </nav>
            </div>
          </header>

          {/* Add padding top to account for fixed header */}
          <main className="flex-1 pt-16">{children}</main>
        </div>
      </body>
    </html>
  );
}
