"use client";

import React from "react";
import { motion } from "framer-motion";

type Props = {
  onPrimary?: () => void;
};

export default function Hero({ onPrimary }: Props) {
  return (
    <section className="mx-auto max-w-5xl py-16 px-6">
      <div className="grid gap-8 md:grid-cols-2 md:items-center">
        <motion.div
          initial={{ opacity: 0, x: -30 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6 }}
        >
          <h1 className="text-4xl font-bold leading-tight">AI Fitness Coach</h1>
          <p className="mt-4 max-w-xl text-lg text-zinc-700">Personalized workout and nutrition plans, generated by AI and tailored to your goals.</p>

          <div className="mt-6 flex gap-3">
            <button
              onClick={onPrimary}
              className="rounded bg-indigo-600 px-5 py-3 text-white hover:bg-indigo-700"
            >
              Generate My Plan
            </button>
            <a href="/saved" className="rounded border px-5 py-3">Saved Plans</a>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, x: 30 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="rounded-lg bg-gradient-to-br from-indigo-50 to-pink-50 p-6">
            <h3 className="font-medium">Quick demo</h3>
            <p className="mt-2 text-sm text-zinc-600">Create a plan in a few steps — workouts, diet, tips, and voice playback.</p>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
